### ISSUE TITLE
splunk-1.6.2.0.jar  contains classes twice

### ISSUE THREAD

**Issue by tim-suchanek** [splunk/splunk-sdk-java#102]
https://github.com/splunk/splunk-sdk-java/issues/83 is marked closed with 1.6.2 - but upgrading the version did not fix the issue on our side. A look into the jar revealed that old classes seem to reside next to the new ones. Can you please verify and re-package please?

**Comment by shakeelmohamed** [comment]
@tim-suchanek can you see if this is fixed in v1.6.3?
