### ISSUE TITLE
Entity object does not contain the "updated" field

### ISSUE THREAD

**Issue by vettal-wu** [splunk/splunk-sdk-java#103]
When we send splunkd a rest api to get the entity, there exists a field "updated" in the response which means the last modified time of this entity. This value may be useful in some cases. For example, some apps want to sort the objects according to the last modified time.

But in java sdk, this field is skipped after parsing the response to an entity, and we can't get the value. I think it's necessary for sdk to provide this field in entity object.

**Comment by shakeelmohamed** [comment]
Merged to develop with #104
