### ISSUE TITLE
pom.xml missing dependencies

### ISSUE THREAD

**Issue by kozlicki** [splunk/splunk-sdk-java#106]
for following artifacts
- gson-2.2.4.jar
- opencsv-2.3.jar
- commons-cli-1.2.jar

**Comment by shakeelmohamed** [comment]
Thanks @kozlicki, we've filed a task internally to take care of this DVPL-7285

**Comment by pebo** [comment]
Any progress on this issue? Have you also considered to use more recent versions of the dependencies (gson 2.2.4 is from 2013: https://github.com/google/gson/blob/master/CHANGELOG.md)

**Comment by aggie05engineer** [comment]
To save the next developer some time - this worked for me to get our Gradle builds happy:

```
dependencies {
    implementation 'com.splunk:splunk'

    components {
        withModule('com.splunk:splunk') {
            allVariants {
            withDependencies { dependencies ->
                dependencies.add('com.google.code.gson:gson')
            }
            }
        }
    }
}
```

**Comment by bparmar-splunk** [comment]
Hi @kozlicki,
We have migrated SDK build from Ant to Maven build. And all required dependencies are upgraded to recent versions.
And @pebo, yes we have considered recent version of gson dependency.

We recommend to update your current SDK to latest version (i.e. [v1.7.1](https://github.com/splunk/splunk-sdk-java/releases/tag/1.7.1)) along with JDK 1.8 and Maven build.

Please let us know if you face any issues.
