### ISSUE TITLE
Value.toDate(string value) is not thread safe

### ISSUE THREAD

**Issue by philippeu** [splunk/splunk-sdk-java#108]
When running the sdk in multi-threaded environment, method `static Date toDate(String value) ` in class `Value` is throwing exceptions from time to time:

- Caused by: java.lang.NumberFormatException: For input string: ""
- Caused by: java.lang.NumberFormatException: For input string: ".10201E.102014E4"
- Caused by: java.lang.NumberFormatException: multiple points

This is preventing to get the status of a job.
Here is  [some hints](https://stackoverflow.com/questions/4021151/java-dateformat-is-not-threadsafe-what-does-this-leads-to) to fix this issue
thanks

**Comment by daelfdude** [comment]
We have run into this same issue as well.  Random but frequent occurrences that only started with the recent update to 1.6.3.   We are falling back to 1.6.2 until this is resolved.

**Comment by shakeelmohamed** [comment]
We've merged a fix to the develop branch.
