### ISSUE TITLE
Modular Input - java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SplunkingArnaud** [splunk/splunk-sdk-java#119]
Hello, 

I am trying to implement a Java Modular input.
I am using splunk-sdk-java.

When trying to use the writeEvent method or synchronizedWriteEvent from the eventwriter i get an exception:
java.lang.ArrayIndexOutOfBoundsException.

Could you please advise.

This issue seems to be similar to this one:
https://answers.splunk.com/answers/577416/java-modular-input-javaxxmlstreamxmlstreamexceptio.html

Best regards.

**Comment by smndf** [comment]
Hello,
I am facing exactly the same issue, any update?
Tested on Splunk 7.2.6 with sdk 1.6.5.0 on ubuntu 18.04 with Java 8 or 11
Best regards

**Comment by bparmar-splunk** [comment]
Hi @SplunkingArnaud & @smndf,
We have tried to reproduce this issue using one of the test case available with us. We could not encounter such behaviour.

Also, we recommend users to update your sdk to updated version ([v1.7.1](https://github.com/splunk/splunk-sdk-java/releases/tag/1.7.1)) along with JDK 1.8 and Maven build.
