### ISSUE TITLE
Modular Input - textInNode throwing exception when input string is empty

### ISSUE THREAD

**Issue by segfault-** [splunk/splunk-sdk-java#122]
Version of this project you're using 1.6.4
Platform version osx 10.13.3 (high sierra)
Framework version java 1.8.0_131
Splunk version 7.0.2 - 03bbabbd5c0f

Other relevant information (ex: local/remote environment, Splunk network configuration)

I tracked down this bug because at surface level, it appeared that input validation was not being executed.  Indeed it wasn't being executed because XmlUtil.textInNode would throw an exception when encountering an argument with a null/empty value.  

I have a proposed fix below that seems to work on 7.0.2, but i can't speak to backwards compatibility with older versions of splunk

com.splunk.modularinput.XmlUtil.textInNode(XmlUtil.java:38)\\com.splunk.modularinput.Parameter.nodeToParameterList(Parameter.java:72)\\com.splunk.modularinput.ValidationDefinition.parseDefinition(ValidationDefinition.java:245)\\com.splunk.modularinput.Script.run(Script.java:85)\\com.splunk.modularinput.Script.run(Script.java:44)...

fix in my env
     static String textInNode(Node node, String errorMessage) throws MalformedDataException {
         Node child = node.getFirstChild();
-        if (child.getNodeType() != Node.TEXT_NODE) {
-            throw new MalformedDataException(errorMessage);
-        } else {
-            return ((Text)child).getData();
+        if(child != null) {
+	        if (child.getNodeType() != Node.TEXT_NODE) {
+	            throw new MalformedDataException(errorMessage);
+	        } else {
+	            return ((Text)child).getData();
+	        }
         }
+        
+        return("");
     }

**Comment by segfault-** [comment]
my formatting didn't go thru, i just added a child!=null check

**Comment by shakeelmohamed** [comment]
Hi @segfault-, thanks for you note. Feel free to open a pull request if there's a specific change you'd like to see

**Comment by jrobins04** [comment]
Hi @bparmar-splunk,

I am able to reproduce this using v1.9.1. This issue happens when the user provides no value for a modular input parameter. 
com.splunk.modularinput.XmlUtil::textInNode line number 38:
```
static String textInNode(Node node, String errorMessage) throws MalformedDataException {
        Node child = node.getFirstChild();
        if (child.getNodeType() != Node.TEXT_NODE) {
            throw new MalformedDataException(errorMessage);
        } else {
            return ((Text)child).getData();
        }
    }
```

Here no null check is performed for the `child` variable. In case when the modular input parameter has no value, `child` will be null and `child.getNodeType()` leads to null pointer.

Please let me know if you need any other information regarding this issue.
