### ISSUE TITLE
Modular Input - Set Token - vs "login"  - sessionkey and kvstore

### ISSUE THREAD

**Issue by segfault-** [splunk/splunk-sdk-java#123]
method "setToken" doesn't append "Splunk " at the start of the sessionKey.  Method login will set the token as "Splunk " + sessionKey (see below).

public Service login(String username, String password) {
        ...
        this.token = "Splunk " + sessionKey;
        ...
    }

This can cause issues when working with a modular input and wanting to make REST calls to say.....kvstore

I have to add the "Splunk " + sessionKey  -- which is fine, but i feel like their should be a documented example and maybe an explicit method.  

ServiceArgs serviceArgs = new ServiceArgs();
		           
serviceArgs.setHost("localhost");
serviceArgs.setToken("Splunk " + sessionKey);
serviceArgs.setPort(8089);
serviceArgs.setScheme("https");
serviceArgs.setApp("kvstore");

Service splunkService = Service.connect(serviceArgs);

RequestMessage requestMessage = new RequestMessage("GET");
ResponseMessage rm = splunkService.send(..., requestMessage);

**Comment by shakeelmohamed** [comment]
Hi @segfault-, thanks for you note. Feel free to open a pull request if there's a specific change you'd like to see
