### ISSUE TITLE
java.io.IOException: Push back buffer is full when exporting data in XML

### ISSUE THREAD

**Issue by vergnes** [splunk/splunk-sdk-java#124]
When calling the export API in XML,Splunkd might write a lot of spaces before the first XML tag (see attachment). The InsertRootElementFilterInputStream class assumes that a buffer of 512 bytes is enough to find the first opening tag. As a result the following exception is raised: [java.io|http://java.io/].IOException: Push back buffer is full 

Internally tracked by DVPL-7313

**Comment by tdhellmann** [comment]
For the record this is addressed in the PR here: https://github.com/splunk/splunk-sdk-java/pull/125

**Comment by fantavlik** [comment]
Merged/released in v1.6.5
