### ISSUE TITLE
I can not run the example

### ISSUE THREAD

**Issue by DirtyDeedsDoneDitryCheap** [splunk/splunk-sdk-java#127]
Now I download the project and want to run example in eclipse.When I debug,for example,I debug at "package com.splunk.examples.index" ,execute the main method,I found that it get a url http://localhost:8000/services/auth/login ,but return com.splunk.HttpException: HTTP 404.
I had download and install splunk by click "download it here".And I can login in http://localhost:8000,using the splunk at  browser.
My file ".splunkrc" is:
host=localhost
port=8000
username=admin
password=123.QWER
scheme=http
version=5.0

When I want to run example,erros at com.splunk.Service.login(Service.java:1128).
How can I run exampls?Is my environment wrong?

**Comment by shakeelmohamed** [comment]
Hi @DirtyDeedsDoneDitryCheap,

The SDK uses the REST API port (8089 by default) and https by default. Change those 2 things and it should start working.

Please re-open if that doesn't work.

**Comment by DirtyDeedsDoneDitryCheap** [comment]
@shakeelmohamed  Thanks for your answer.
I've tried to use https and 8089 with the erro  javax.net.ssl.SSLHandshakeException like
https://github.com/splunk/splunk-sdk-java/issues/113   
So I want to use http and 8000. Now I use https and 8089,altering the HttpService.java like https://github.com/splunk/splunk-sdk-java/pull/114/files
I have successfully run example.

**Comment by shakeelmohamed** [comment]
In that case, just add `Service.setSslSecurityProtocol(SSLSecurityProtocol.TLSv1_2);` at the beginning of the example and it should work.

**Comment by knagarohit** [comment]
I still get the same error with JAVA 8, can anyone help me in resolving the issue to connect to Splunk?

**Comment by knagarohit** [comment]
@shakeelmohamed @DirtyDeedsDoneDitryCheap Were you able to connect to Splunk using HTTP and localhost?
