### ISSUE TITLE
splunk service return 404 not found - Java SDK

### ISSUE THREAD

**Issue by Ikenahim** [splunk/splunk-sdk-java#133]
This method make request to Splunk:

HttpService.setSslSecurityProtocol(SSLSecurityProtocol.TLSv1_2);

        Service service = new Service(host,port);
        String credential = user_name+":"+pasword;
        String basicAuthHeader  = Base64.getEncoder().encodeToString(credential.getBytes());

        service.setToken("Basic"+basicAuthHeader);

        if(service.getToken()!= null)
        {
            this.token = service.getToken();
            Authenticated();
        }

        return  service;

when I user service to create Job I got error 404 not found, knowing that I got token back.
what is the issue? 

Thanks

**Comment by Ikenahim** [comment]
This where I use Service to create query:

public ResultsReaderJson parse_Scan_Data()
    {
        String Query = "index=nessus earliest=-1w |eval base=tonumber(cvss_base_score)| search (base>7.5) AND (ports{}.port!=0)";

        Job job = session.make_Request().getJobs().create(Query);

        while(!job.isDone())
        {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        JobResultsArgs resultsArgs = new JobResultsArgs();
        resultsArgs.setOutputMode(JobResultsArgs.OutputMode.JSON);
        InputStream results = job.getResults(resultsArgs);
        try
        {
            ResultsReaderJson resultsReader = new ResultsReaderJson(results);
            return  resultsReader; // to be tested
        } catch (IOException e)
        {
            e.printStackTrace();
        }
        return null;
    }

**Comment by shakeelmohamed** [comment]
What port value are you using?

Is there any reason you can't use the `Service(Map<String, Object> args)` constructor, or `Service.login()` as I've shown below?

```diff
    Service service = new Service(host,port);
++  service.login(user_name, pasword);
--  String credential = user_name+":"+pasword;
--  String basicAuthHeader  = Base64.getEncoder().encodeToString(credential.getBytes());

--  service.setToken("Basic"+basicAuthHeader);

    if(service.getToken()!= null)
    {
        this.token = service.getToken();
        Authenticated();
    }

    return  service;
```

**Comment by Ikenahim** [comment]
I use 443 as Splunk is hosted in host with https protocol.
and for host I use Ip address of the host 
I used that method since I want to see one session to request query to Splunk without the need to log for each time I want to perform a query

**Comment by shakeelmohamed** [comment]
@Ikenahim The REST API uses port 8089 for Splunk Enterprise, are you using Splunk Cloud? If so, what's the host value?

The Java SDK has support for cookie-based authentication so you can login once per `Service` instance and you'll continue to get new tokens behind the scenes if you continue making requests.

**Comment by Ikenahim** [comment]
what is the best approach to login? is it good idea to login for each request ? 
I'm using Splunk enterprise.

**Comment by shakeelmohamed** [comment]
@Ikenahim can you show how you're using the SDK exactly? Once you login with a Service object you shouldn't need to login again for each request

**Comment by Ikenahim** [comment]
I have fixed that, it was an issue with firewall rules.
I have another problem right with URI cant be null! I have searched this they suggest to add 
        HttpService.setSslSecurityProtocol(SSLSecurityProtocol.TLSv1_2);

before making the request which I did but still same problem? how to fix this knowing that I'm using Java sdk 11

Thank you

**Comment by shakeelmohamed** [comment]
@Ikenahim can you share your anonymized code that uses the SDK? If you don't want to share it publicly, please email us at devinfo@splunk.com

We are unable to help you until we know exactly what you're trying to accomplish.

**Comment by Ikenahim** [comment]
This was fixed, was an issue with SSL certificate, a team from security department has fixed this issue . Thank you
