### ISSUE TITLE
Service.login() does not work well with long-lived clients

### ISSUE THREAD

**Issue by aggie05engineer** [splunk/splunk-sdk-java#139]
It appears that `Service.login()` is the correct way to log into Splunk and retrieve a cookie containing a token value. For long running applications this token/cookie will eventually expire. There does not appear to be an idiomatic way to refresh these tokens or know when the cookie expires (or should expire).

One approach seems to require every interaction to `login()` (for threading and expiration reasons). This is requires a round-trip for every Service interaction. The `login()` code appears written to no-op if already logged in but it checks for `null` user and password fields to no-op and the user/password fields are never unset. The API does not make it clear that you should null these fields for no-op to take place.

From the code comments:

    /**
     * Authenticates the {@code Service} instance with the username and password
     * that were specified when the instance was created.
     *
     * Three cases:
     * 1. If we have a cookie, but are missing username and/or password, login is noop
     * 2. If we don't have a cookie, and are missing username and/or password we can't login
     * 3.  Otherwise login as usual
     *
     * @return The current {@code Service} instance.
     */
    public Service login() {

Even if you set username and password to `null` the cookie eventually expires and you get back a generic HttpException:

    com.splunk.HttpException: HTTP 401 -- {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}

There is no easy way to deduce cookies have likely expired.

What is the idiomatic way to use the java SDK for long-lived applications? Should we login() for every interaction? If we need to refresh cookies - what is the recommended way to do that? Just poll `login()` on some cadence?

Thank you!

**Comment by bparmar-splunk** [comment]
Hi @aggie05engineer,
We recommend users to make use of **Bearer** token (going further) instead of Splunk token, because it is configurable and long lived.

**Comment by kaiseu** [comment]
@bparmar-splunk do we have an example on how to use Bearer token for long lived search? thanks
