### ISSUE TITLE
Connection Reset after some requests to splunk api

### ISSUE THREAD

**Issue by v-blan** [splunk/splunk-sdk-java#144]
Hi team, 

We are using splunk jdk 1.6.4. 

Recently , we got a lot of connection reset error  when we try to send requests to splunk api . And we need wait it for more than a minite then we can send our requests again. Do you guys have any idea about this?

Here is our setting in code:
HttpService.setSslSecurityProtocol(SSLSecurityProtocol.TLSv1_2 );
ServiceArgs serviceArgs = new ServiceArgs();
        serviceArgs.setUsername(username);
        serviceArgs.setPassword(password);
        serviceArgs.setHost(host);
        serviceArgs.setPort(8089);
        serviceArgs.setScheme("https");
Service connect = Service.connect(serviceArgs);

Here is our dependency in our pom file:
<dependency>
            <groupId>com.splunk</groupId>
            <artifactId>splunk</artifactId>
            <version>1.6.4.0</version>
        </dependency>

Here is our part of error log:
java.lang.RuntimeException: Connection reset
	at com.splunk.HttpService.send(HttpService.java:451) ~[splunk-1.6.4.0.jar!/:1.6.4]
	at com.splunk.Service.send(Service.java:1295) ~[splunk-1.6.4.0.jar!/:1.6.4]
	at com.splunk.HttpService.post(HttpService.java:348) ~[splunk-1.6.4.0.jar!/:1.6.4]
	at com.splunk.Service.login(Service.java:1124) ~[splunk-1.6.4.0.jar!/:1.6.4]
	at com.splunk.Service.login(Service.java:1103) ~[splunk-1.6.4.0.jar!/:1.6.4]
	at com.splunk.Service.connect(Service.java:189) ~[splunk-1.6.4.0.jar!/:1.6.4]

**Comment by ncanumalla-splunk** [comment]
similar to #145

**Comment by bparmar-splunk** [comment]
Hi @v-blan,
We have tried to reproduce this issue, but could not make it, and seems resolved.

Please let us know, if you still face this issue and also share more details to reproduce.

**Comment by JayarajJapagal** [comment]
Hi @v-blan 

Is this issue resolved ?
I am also facing same problem
