### ISSUE TITLE
getting java.io.IOException: Premature EOF while fetching data from splunk

### ISSUE THREAD

**Issue by avaz-splunk** [splunk/splunk-sdk-java#147]
We are running a search query through Splunk SDK using rest end point and publishing the data to an index. which in turn writes the output data to Excel file. While writing the output data we are seeing exception error intermittently in splunk. As a workaround we have implemented a retry method to reconnect to splunk and this was working fine for sometime but now again we are seeing the same exception error intermittently. 

Error Message: java.util.concurrent.ExecutionException: java.io.IOException: Premature EOF 

Splunk rest user – qesserviceswebsplunkuser_e2e 
Splunk sdk - 1.6.3.0 
Java jdk – 1.8

**Comment by avaz-splunk** [comment]
@splunk support, any update on this issue? we need to unblock a user asap on this issue

**Comment by ncanumalla-splunk** [comment]
@avaz-splunk Please let us know if you are still facing this issue or have found a resolution. Thanks.
