### ISSUE TITLE
Need a way to turn on TLS hostname verification

### ISSUE THREAD

**Issue by fpan-splunk** [splunk/splunk-sdk-java#156]
It seems we hardcode it to always pass the hostname verification.
We need a way to be able to specify a hostname verifier so that the customer can turn on the hostname verification if they want

https://github.com/splunk/splunk-sdk-java/blob/ffe45f87b8edfde5bbae55e592c78859426942f8/splunk/com/splunk/HttpService.java#L44

**Comment by fantavlik** [comment]
Hello! This is currently being addressed in https://github.com/splunk/splunk-sdk-java/pull/158 - which we will release within the next two weeks

**Comment by ashah-splunk** [comment]
Hi @fpan-splunk 
We have updated the HTTPService class for hostname verification and TLS which is available in the latest version of sdk [1.7.1](https://github.com/splunk/splunk-sdk-java/releases/tag/1.7.1) .
SDK build has been migrated to Maven from ant. And we would recommend use of JDK v1.8 with the latest sdk version
