### ISSUE TITLE
how to add custom header if we use AWS API Gateway X-API-Key validation

### ISSUE THREAD

**Issue by dhavamanisettiyannan-nbcuni** [splunk/splunk-sdk-java#169]
We are using Splunk Java SDK for test suite integration that will do search in Splunk and based on search results will decide whether test case pass/fail for Application continues integration and deployment pipeline. We have introduced AWS API Gateway with X-API-Key validation for security requirement. Can you please let us know how to add custom header X-API-Key to each Splunk Java SDK calls.

**Comment by ncanumalla-splunk** [comment]
@dhavamanisettiyannan-nbcuni Thank you for the question. Today, the Splunk Java SDK does not support passing custom headers. There is a [static map of headers](https://github.com/splunk/splunk-sdk-java/blob/master/splunk/src/main/java/com/splunk/HttpService.java#L82-L85) inside the SDK but it is not open to customize. 
We will need to prioritize this as a feature enhancement. Is there a time by which you need this?
We are open to contributions and can get to this sooner if you'd like to submit a PR.

**Comment by dhavamanisettiyannan-nbcuni** [comment]
@ncanumalla-splunk Thank you for the update, Can you please prioritize and implement this feature at least by end of November 2021.

**Comment by ncanumalla-splunk** [comment]
Thank you for the information to help prioritize. Will plan accordingly.

**Comment by BalasubramanyamEvani** [comment]
@ncanumalla-splunk can I take this up? new to this repository. I think a setter method needs to be implemented which accepts a map and merges with the defaultHeaders. I do have a doubt though while accepting a new map of headers, how to handle the case when we get duplicate keys - Ignore or Merge values? Also, I guess a check needs to be in place to check for **User-Agent, Accept** keys?

Let me know if I can work on this and if my understanding is correct. Thanks!

**Comment by ncanumalla-splunk** [comment]
@BalasubramanyamEvani We definitely welcome contributions. Your approach seems to be in the right direction. Yes, you will need to account for the default keys and avoid overriding values. Please try implementing this as part of the [ServiceArgs](https://github.com/splunk/splunk-sdk-java/blob/master/splunk/src/main/java/com/splunk/ServiceArgs.java) class. Please submit a PR to this repo and our team can review.

**Comment by BalasubramanyamEvani** [comment]
@ncanumalla-splunk Thanks ! will work on it

**Comment by bparmar-splunk** [comment]
@BalasubramanyamEvani,
Will you please share current status of this issue? We would like to know if you are planning a PR for the same.
Please let us know in case of any queries/details.

**Comment by BalasubramanyamEvani** [comment]
Yes i am planning to submit a PR by this week. I've been busy with Job search, sorry for the delay.

**Comment by bparmar-splunk** [comment]
@BalasubramanyamEvani,
Thank you for the update.
Please let us know when you create PR.

**Comment by bparmar-splunk** [comment]
@BalasubramanyamEvani,
Could you please re-share the timeline for this issue resolution?
As we are planning to release this change in this week. 
Please let us know, if you have further queries.

**Comment by BalasubramanyamEvani** [comment]
Hello @bparmar-splunk  sorry for the delay. I have created PR #176. Please check

**Comment by fantavlik** [comment]
Merged in https://github.com/splunk/splunk-sdk-java/pull/176
