### ISSUE TITLE
SSL ValidateCertificates Still Attempts to Validate When Set to False

### ISSUE THREAD

**Issue by cgivre** [splunk/splunk-sdk-java#204]
Hello all, 

We've been doing some work with the Splunk SDK, and we've found that the new parameter that is supposed to disable SSL certificate validation seems to have no effect.  The result is that on testing machines we get the following error:

```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

We have found a workaround, however, I wanted to flag this for your team as you might want to fix it.

**Comment by ashah-splunk** [comment]
Hi @cgivre Sorry for the delay in response. 
As per the analysis we found that the sequence in which the code statements are executed is resulting in exception. [Ref ](https://github.com/apache/drill/pull/2719/files#diff-4ad298c0f22310061b4021eb481dd946a9fb15d4fc183edf003cd871b1907183R114-R115)
The required sequence is to  call `setValidateCertificates` before `setSslSecurityProtocol` method i.e:-
```java
HttpService.setValidateCertificates(validateCertificates);
HttpService.setSslSecurityProtocol(SSLSecurityProtocol.TLSv1_2);
```
Request you to update the code as per the above sequence and let us know if you still face the issue.
Also thanks for bringing this to our notice we will work on updating this information in the docs to avoid such issues in future.

**Comment by jnturton** [comment]
@cgivre @ashah-splunk changing the call sequence as suggested above is only a workaround to this bug if an SSL protocol that is _different to the one set previously_ is provided in the call to HttpService.setSslSecurityProtocol. In this case the creation of a new SSLSocketFactory be triggered, and the validateCertificates option be applied.

**Comment by ashah-splunk** [comment]
@jnturton yes changing the sequence is a workaround. We have already made the necessary changes in the SDK on the similar lines that you described (Ref [PR](https://github.com/splunk/splunk-sdk-java/pull/206/files)). The changes will be available in the next Release, till that we request you to apply the workaround. Will update you once we have a new release published.

**Comment by ashah-splunk** [comment]
@cgivre , @jnturton the necessary changes have been merged in the latest release of the Splunk Java SDK request you to test with the latest version and let us know if you are still facing the issue. sorry for the delay in the update.
