### ISSUE TITLE
Please publish to maven central

### ISSUE THREAD

**Issue by binkley** [splunk/splunk-sdk-java#66]
I appreciate you do use Maven, and know that you host your own repository.  Please consider publishing to Maven central.  There are a slew of tools and integrations that know to look for dependencies in Maven central - then splunk.jar would "just work out of the box" as a dependency.

**Comment by sunieldalal** [comment]
I am also hoping that it will be published soon to maven central so that it gets easier for developers

**Comment by shakeelmohamed** [comment]
We're going to close this now. Internally we've made a firm stand that we will not publish to maven central. The workaround is simply using the maven repository configuration we have in the readme.
