### ISSUE TITLE
Allow connection through proxy 

### ISSUE THREAD

**Issue by wpoch** [splunk/splunk-sdk-java#79]
Do you have any plans to implement the connection through proxies?

**Comment by itay** [comment]
@wpoch it's something that is in our backlog, but we have no immediate plans. We're always open to receiving pull requests for things like this that include the code changes and tests to go with them.

**Comment by wpoch** [comment]
Ok, I will try to make the pull request for this.

**Comment by itay** [comment]
Closing until there is some movement on this.

**Comment by dstaas** [comment]
I was able to modify the Splunk 1.6.0 Java SDK to enable our corporate proxy to work against Splunk 6.4.1.  I made changes in 2 places:

In HttpService.java, changed line 41 to TLS_v1.2 (was SSLv3):

    protected static SSLSecurityProtocol sslSecurityProtocol = SSLSecurityProtocol.TLSv1_2;

around line 406, added a single line for our proxy server, e.g.

    Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("web-proxy", 8080));
    cn = (HttpURLConnection) url.openConnection(proxy);

I'll see if I can get this is a bit more supportable form and submit it as a pull request.  This code should probably check for the Java system properties http.proxyHost and http.proxyPort and use those values above if set.

**Comment by shakeelmohamed** [comment]
Thanks for looking into this @dstaas

**Comment by dstaas** [comment]
Still working on getting internal approval to submit PR, please leave open & I'll get it in as soon as I can.

**Comment by shakeelmohamed** [comment]
@dstaas due to inactivity we are closing this issue. Feel free to send us a pull request at anytime.
