### ISSUE TITLE
Overriding for Password.itemKey is not reasonable

### ISSUE THREAD

**Issue by fuyufjh** [splunk/splunk-sdk-java#85]
In `PasswordCollection.java`

``` java
 /**
 * Returns the username for a credential.
 *
 * @param entry The {@code AtomEntry} object describing the credential.
 * @return The username.
 */
@Override protected String itemKey(AtomEntry entry) {
    return (String)entry.content.get("username");
}
```

I don't think this is is reasonable because a certain password is located by id "[realm]:[username]". Assuming you have 2 password, first is "realmA:admin" and second is "realmB:admin", `passwordCollection.get("admin")` can only return one of it

Suggesting overriding `passwordCollection.get(String id)` and an additional `passwordCollection.get(String realm, String name)`.

**Comment by itay** [comment]
@fuyufjh sounds like a decent idea. A pull request is welcome to fix it :)

**Comment by shakeelmohamed** [comment]
Merged to the develop branch
