### ISSUE TITLE
Error Messages of a search 

### ISSUE THREAD

**Issue by ranugant** [splunk/splunk-sdk-java#87]
Hello Team,
My search results are incomplete due to some of the indexes were down
![splunk](https://cloud.githubusercontent.com/assets/22604491/19057171/dac79330-8982-11e6-8d1e-ff78ae7ba998.jpg)
Got Some warnings and error messages,  is there any way to retrieve them using splunk java sdk as its showing job has property called messages but i didnt find that property in sdk 1.5.0.

Please help me out in getting those error message as i need to send those errors to end users.

Thanks,
Ranaveer

**Comment by shakeelmohamed** [comment]
Hi @ranugant,

You can access the `getSearchLog()` method on any `Job` object

**Comment by ranugant** [comment]
Hi Shakeel,

Thanks for your response. I tried reading that searchlog but i couldn't find any error information in that log.

**Comment by shakeelmohamed** [comment]
@ranugant can you try calling `get("messages")` on the `Job` object? That should return a map of severity levels to messages

**Comment by ranugant** [comment]
Hi Shakeel,

It worked. Thank you so much for your help.
good work keep it up.
