### ISSUE TITLE
bug: java modular input launchers in windows may not kill java process when it be terminated

### ISSUE THREAD

**Issue by vettal-wu** [splunk/splunk-sdk-java#92]
I run modular input using shim.exe in windows.

When I stop splunk, I found that the shim.exe process will be killed, but the java process is still running. And in splunkd.log, there is a warning messages:

```
WARN  ProcessRunner - Process with pid 4840 did not exit within a given grace period after being signaled to exit. Will have to forcibly terminate.
```

Process 4840 is the shim.exe.

I read the code of shim.cpp. I found that shim.exe will wait splunkd and java process using function ```waitOutcome = WaitForMultipleObjects(2, processHandles, FALSE, INFINITE);```. If splunkd is stopping, it will be signaled and this function will return. Then we can send CTRL+C signal to java process. 

But as I found, shim.exe can't exit gracefully within the given grace period. So it is terminated by splunk and will not send CTRL+C signal to java process. I still don't know how long the given grace period.

I think even if the shim.exe be terminated, we should also ensure the related java process be killed.

**Comment by shakeelmohamed** [comment]
PR has been merged to develop
