### ISSUE TITLE
update used version of minified $script

### ISSUE THREAD

**Issue by poet-of-the-fall** [splunk/splunk-sdk-java#96]
Hi,

I use the SDK together with Angular 2. Painting one chart was no problem, but as I wanted to paint a second one, it didn't work. I traced it down to the "UI.loadCharting" function. The passed callback is only called, if $script loads the file from the server. If using the function for creating a second chart, the callback will not be executed (as the file is already loaded).
I fixed it by replacing the included minified version of $script by the current one.

**Comment by tdhellmann** [comment]
Hi @poet-of-the-fall - was this meant for the [JS SDK](https://github.com/splunk/splunk-sdk-javascript)?

**Comment by poet-of-the-fall** [comment]
oh sorry, yes, wrong repo :-(
